name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The next release tag to use'
        required: false
        type: string
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      # - name: Env
      #   run: |
      #     # ACTIONS_RUNTIME_TOKEN, ACTIONS_RUNTIME_URL should be exposed
      #     env|sort
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.tag }}
      - name: Zip it up
        run: zip -r 'mi.Immich.Publisher.lrplugin.zip' . -x '*.git*'
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          removeArtifacts: true
          artifacts: "mi.Immich.Publisher.lrplugin.zip"
          allowUpdates: true